language: ruby
rvm: 2.6.5
bundler_args: --without production
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - rake assets:precompile
install:
  - nvm install 10
  - yarn
  - bundle install --jobs=3 --retry=3
cache:
  yarn: true
