language: ruby
rvm: 2.4.1
bundler_args: --without production
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
install:
  - nvm install 8
  - yarn
  - bundle install --jobs=3 --retry=3
cache:
  yarn: true
