---
# This is the file used by Ansible to provision your project
# You can decide what you want to install in your box by choosing
# various provided roles or add tasks to this file. If you need
# more explanation, please refer to the drifter README

# For some part, multiple roles are proposed, just uncomment the ones
# you need.

- hosts: all
  vars_files:
   - parameters.yml
  become: no

  roles:
    - { role: base }
    - { role: git }
    - { role: nginx, web_directory: "/vagrant/public", site_template: "rails-site.j2", proxy_port: 5000 }
    - { role: postgresql }
    - { role: ruby }
    - { role: nodejs }

  tasks:
    - name: Copy database configuration file
      copy:
        src: /vagrant/config/database.example.yml
        dest: /vagrant/config/database.yml
        force: no
